common.gradle, sdk/src/main/java/com/uid2/sdk/UID2Client.kt, sdk/src/main/java/com/uid2/sdk/UID2Exception.kt, sdk/src/main/java/com/uid2/sdk/network/DefaultNetworkSession.kt, sdk/src/main/java/com/uid2/sdk/network/NetworkSession.kt, sdk/src/main/java/com/uid2/sdk/network/RefreshResponse.kt, sdk/src/test/assets/test-data/identity-valid.json, sdk/src/test/assets/test-data/refresh-token-200-expired-decrypted.json, sdk/src/test/java/com/uid2/sdk/UID2ClientTest.kt, sdk/src/test/java/com/uid2/sdk/data/TestData.kt, sdk/src/test/java/com/uid2/sdk/data/UID2IdentityTest.kt, sdk/src/test/java/com/uid2/sdk/network/DefaultNetworkSessionTest.kt, sdk/src/test/java/com/uid2/sdk/network/RefreshResponseTest.kt
- Implementation of the `UID2Client` class. This is responsible for refreshing a token/identity. It makes the request, via the `NetworkSession` interface, decodes the output via the `DataEnvelope` and parses the response. After fleshing out this class, I decided to modify the `NetworkSession` to improve how it was utilised.
- In a previous PR, I suggested porting a number of uses within `TestData` to be JSON based files, which i've done. I also took the advice on adding more tests around invalid responses, where I can programmatically take a valid response and tweak it (remove stuff) and verify the system behaved. This actually allowed me to find an issue with the code, where a "success" could be returned but without a valid UID2Identity.
=> Implement UID2Client and improve unit test coverage

sdk/src/main/java/com/uid2/sdk/UID2Manager.kt, sdk/src/main/java/com/uid2/sdk/utils/TimeUtils.kt, sdk/src/test/java/com/uid2/sdk/UID2ManagerTest.kt
This PR implements support for automatically refreshing the UID2Identity. After some consideration, I decided to go for a fairly basic approach:
- When loading an identity from persistence, we will immediately check if it's suitable to be refreshed.
- When an identity is set, or loaded from persistence, and is not yet ready to be refreshed, we will calculate the number of seconds until it can be. This will then be scheduled via the Dispatcher. If this scheduled time falls during when the consuming application is still running, then it will be refreshed. Otherwise, the Job will not execute and we will check (or schedule) again when the app is relaunched and the identity loaded from persistence.
=> Implement automatic identity refreshing

sdk/src/main/java/com/uid2/sdk/UID2.kt, sdk/src/main/java/com/uid2/sdk/UID2Client.kt, sdk/src/test/java/com/uid2/sdk/UID2ClientTest.kt, sdk/src/test/java/com/uid2/sdk/UID2Test.kt
- A way to programmatically query the Version of the SDK (via `UID2.getVersion`)
- A way to programmatically query the individual components of the Version of the SDK (via `UID2.getVersionInfo`)
- An update to the `UID2Client` class to build the included `X-UID2-Client-Version` based upon this version
- Additional Unit Test coverage
=> Add support for version info

build.gradle, common.gradle, dev-app/build.gradle, dev-app/okhttp3-proguard-rules.txt, dev-app/src/main/AndroidManifest.xml, dev-app/src/main/java/com/uid2/dev/DevApplication.kt, dev-app/src/main/java/com/uid2/dev/MainActivity.kt, dev-app/src/main/java/com/uid2/dev/network/AppUID2Client.kt, dev-app/src/main/java/com/uid2/dev/network/AppUID2ClientException.kt, dev-app/src/main/java/com/uid2/dev/network/GenerateTokenResponse.kt, dev-app/src/main/java/com/uid2/dev/network/OkNetworkSession.kt, dev-app/src/main/java/com/uid2/dev/network/RequestType.kt, dev-app/src/main/java/com/uid2/dev/ui/BasicViewModel.kt, dev-app/src/main/java/com/uid2/dev/ui/MainScreen.kt, dev-app/src/main/java/com/uid2/dev/ui/MainScreenViewModel.kt, dev-app/src/main/java/com/uid2/dev/ui/views/ActionButtonView.kt, dev-app/src/main/java/com/uid2/dev/ui/views/EmailInputView.kt, dev-app/src/main/java/com/uid2/dev/ui/views/ErrorView.kt, dev-app/src/main/java/com/uid2/dev/ui/views/LoadingView.kt, dev-app/src/main/java/com/uid2/dev/ui/views/UserIdentityView.kt, dev-app/src/main/res/values/strings.xml, sdk/build.gradle, sdk/src/main/java/com/uid2/network/DefaultNetworkSession.kt
- A simple (and poorly interfaced!) development application that allows testing of the UID2 SDK. This allows the user to enter a made up email address, generate a UID2 token and provide it to the Manager. The Manager will then periodically update the token, based upon the `refreshFrom` attribute. The Dev App also allows for resetting the user, as well as a manual refresh.
- In order to test support for custom Networking, I've implemented a `OkNetworkSession` inside the Dev App. This shows consumers how they may provide a wrapper around OkHttp to have it perform any necessary networking of the SDK.
=> Implement SDK Development Application

sdk/src/main/java/com/uid2/UID2Manager.kt, sdk/src/main/java/com/uid2/storage/SharedPreferencesStorageManager.kt, sdk/src/main/java/com/uid2/storage/StorageManager.kt, sdk/src/test/java/com/uid2/UID2ManagerTest.kt, sdk/src/test/java/com/uid2/storage/SharedPreferencesStorageManagerTest.kt
Access to the identity storage can (and should) be done via an IO dispatcher. We are already async when loading/saving the identity, so makes sense to ensure that this work is being done on an appropriate thread.
=> Migrate storage access over to IO dispatcher

build.gradle, common.gradle, docs/releasing.md, sdk/build.gradle, sdk/src/main/java/com/uid2/UID2.kt, securesignals-gma/src/main/java/com/uid2/securesignals/gma/UID2SecureSignals.kt, securesignals-ima/src/main/java/com/uid2/securesignals/ima/UID2SecureSignals.kt
- Modified versioning to all pull from `build.gradle`
- Modified versioning to allow `-SNAPSHOT` versions
- Integrated plugin for deployment to Maven Central and configured
- Added releasing document to demonstrate how we will release.
=> Implement initial support for SDK deployment

sdk/src/main/java/com/uid2/UID2Manager.kt, sdk/src/main/java/com/uid2/data/IdentityStatus.kt, sdk/src/main/java/com/uid2/storage/SharedPreferencesStorageManager.kt, sdk/src/main/java/com/uid2/storage/StorageManager.kt, sdk/src/test/java/com/uid2/UID2ManagerTest.kt, sdk/src/test/java/com/uid2/storage/SharedPreferencesStorageManagerTest.kt
This PR will add support to persist (and restore) what the previous IdentityStatus is. This is useful to ensure that in the case when a `OPT_OUT` is associated with the user, that this is consistently reported across app launches.
=> Add support to persist identity status

.github/workflows/publish.yml, sdk/build.gradle
This PR adds a new GitHub workflow that will build and publish `master` to MavenCentral.
=> Implement workflow to publish to Maven

dev-app/src/main/java/com/uid2/dev/ui/MainScreenViewModel.kt, sdk/src/main/java/com/uid2/UID2Manager.kt, sdk/src/test/java/com/uid2/UID2ManagerTest.kt
Since the `UID2Manager` is designed to be reactive, I wanted to introduce a mechanism to detect when it's status changes to `Expired` and also `RefreshExpires`. This is decoupled from the general refresh logic, as that can be enabled or disabled by the user.
This PR adds a simple mechanism to schedule when the manager will check for expiration. While implementing it, I also found a number of issues which have been fixed.
=> Detect expiration times and notify observers

pom.gradle, sdk/build.gradle, securesignals-gma/build.gradle, securesignals-ima/build.gradle
Added maven publication support for the IMA and GMA plugins. They just use a shared pom, since they don't really need anything more specific. The artefact ids are as follows:
- uid2-android-sdk
- uid2-android-sdk-ima
- uid2-android-sdk-gma
For testing, I temporarily modified the `publish.yml` to include this branch. I was able to successfully deploy a snapshot from all three modules.
=> Add support to deploy IMA/GMA plugins

sdk/src/main/java/com/uid2/UID2Manager.kt, settings.gradle
Identified a few small tweaks that needed to be made while testing the consumption of a Snapshot build from the DevApp. Since a Snapshot comes from a different repository than (Normal) MavenCentral, I had to add the extra repository. This is what is required to test the Dev App:
```
diff --git a/dev-app/build.gradle b/dev-app/build.gradle
index 46258e2..f6fe1d8 100644
--- a/dev-app/build.gradle
+++ b/dev-app/build.gradle
@@ -41,7 +41,7 @@ android {
}
dependencies {
-    implementation project(path: ':sdk')
+    implementation 'com.uid2:uid2-android-sdk:0.1.0-SNAPSHOT'
implementation 'androidx.appcompat:appcompat:1.6.1'
implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
```
=> Fix minor issues and test Snapshots

securesignals-ima-dev-app/build.gradle, securesignals-ima-dev-app/src/main/AndroidManifest.xml, securesignals-ima/build.gradle
Restore IMA SDK to 3.30.x level now that issue concerning crashes on non Android TV devices has been resolved with 3.30.1.
https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/history
=> Bump IMA SDK to 3.30.1

dev-app/src/main/AndroidManifest.xml, sdk/src/main/java/com/uid2/UID2Manager.kt, sdk/src/main/java/com/uid2/extensions/ContextEx.kt
The SDK includes a default value for the API URL which potentially could be overwritten by the consuming app. However, it's entirely possible the app doesn't want/need to change it, meaning that it could not have **any** metadata associated with it. In this scenario, the SDK should not crash and should silently just use the default.
=> Remove requirement for Application Metadata

sdk/src/main/java/com/uid2/UID2Manager.kt, sdk/src/test/java/com/uid2/UID2ManagerTest.kt
I found that we were exposed to a number of race conditions, caused by the following:
- The consuming app initialises the manager
- The manager internally kicks off an async task to load state from storage
- If the consuming app **immediately** calls our public API, this can happen **before** we have loaded our initial state
- The initial state will overwrite any modified state set by the consuming app.
This workaround ensures that all public interfaces are aware of the initialisation of the manager. If they occur before, they are suspended until we are ready.
=> Avoid race condition with initialization

README.md, sdk/src/test/java/com/uid2/network/RefreshResponseTest.kt, securesignals-gma-dev-app/build.gradle, securesignals-gma-dev-app/src/main/java/com/uid2/dev/BannerActivity.java, securesignals-gma/build.gradle, securesignals-gma/uid2-gma.pro, securesignals-ima/build.gradle, securesignals-ima/uid2-ima.pro
Since IMA/GMA will load our adapters via reflection, we need to make sure Proguard is configured to avoid these classes being stripped out. The embedded configuration files will be picked up automatically by R8, however, for older builds that use Proguard directly, we will need to update the support documentation to reference them.
=> Add proguard configuration for IMA/GMA plugins

sdk/src/main/java/com/uid2/UID2.kt, sdk/src/test/java/com/uid2/VersionParserTest.kt, securesignals-gma/src/main/java/com/uid2/securesignals/gma/PluginVersion.kt, securesignals-ima/src/main/java/com/uid2/securesignals/ima/PluginVersion.kt
After testing, we've identified that the version parsing wasn't correct. Looks like a silly mistake, and since we have three separate components all using the same code to parse, the bug was in three places :/
=> Fix version parsing for SDK and Plugins

.github/workflows/release.yml
Required as GitHub Actions doesn't have any user info set
=> Set Git user in release workflow

sdk/src/main/java/com/uid2/UID2Manager.kt, sdk/src/test/java/com/uid2/UID2ManagerTest.kt, securesignals-ima-dev-app/build.gradle, securesignals-ima/build.gradle, securesignals-ima/lint-baseline.xml
- When we are automatically refreshing, there is a point when we can't/shouldn't refresh any further. This used to result in an exception being thrown in one of our coroutines, and since there is no `CoroutineExceptionHandler`, this resulted in a fatal exception.
- As requested by @sunnywu, we have changed the refresh behaviour to only stop retrying once the associated identity has expired (fully) and therefore refreshing is not possible. We've also changed the period between refresh attempts, to increase to 60 seconds, after 5 consecutive failures
- Google have deprecated IMA 3.31.X and therefore we are required to downgrade back to the latest stable build, which is 3.29.0
=> Improve automatic refresh behaviour and avoid exception when fails

sdk/build.gradle, securesignals-gma/build.gradle, securesignals-ima/build.gradle
As suggested by @koalaparadise, we should enable `explicitApi` for our SDK based modules. More information about it can be found here: https://kotlinlang.org/docs/whatsnew14.html#explicit-api-mode-for-library-authors
=> Enable explicitApi for SDK modules

gradle.properties
This means that publishing is now fully automatic, after being initiated from GitHub.
=> Enable automatic tagged releases

sdk/src/main/java/com/uid2/UID2Manager.kt, sdk/src/test/java/com/uid2/UID2ManagerTest.kt
This PR adds a new public API to explicitly query if the `UID2Manager` has a known (and valid) identity. The identity may potentially need to be refreshed, but as long as it can, `hasIdentity` will return `true`.
I've also added unit test coverage for a number of the different common cases.
=> Add ability to query if identity is available

dev-app/src/main/java/com/uid2/dev/ui/MainScreenViewModel.kt, sdk/src/main/java/com/uid2/UID2Manager.kt, sdk/src/test/java/com/uid2/UID2ManagerTest.kt
This PR introduces a new mechanism to detect when a `UID2Manager` instance has finished loading any previously persisted identity, which can then be accessed via it's `currentIdentity` property. This is done slightly differently to handle the API required for Kotlin vs Java:
- **Kotlin**: A new `UID2ManagerState` of `Loading` is initially reported. After initialization is complete, the state will update to either reflect `NoIdentity` or one that is appropriate for the identity that was restored.
- **Java**: An explicit callback/listener can be set on the `UID2Manager` instance.
=> Add support to detect when UID2Manager finishes initializing

gradle/libs.versions.toml
Bumping the Android Gradle Plugin to 8.4.0
=> [Dependencies] Bump AGP (8.4.0)

README.md
like https://github.com/IABTechLab/uid2-client-net/blob/main/README.md
=> Make readme.md structure more consistent with C# SDK

dev-app/src/main/AndroidManifest.xml, dev-app/src/main/java/com/uid2/dev/network/AppUID2Client.kt, dev-app/src/main/java/com/uid2/dev/network/AppUID2ClientException.kt, dev-app/src/main/java/com/uid2/dev/ui/MainScreen.kt, dev-app/src/main/java/com/uid2/dev/ui/MainScreenViewModel.kt, dev-app/src/main/java/com/uid2/dev/ui/views/ActionButtonView.kt, dev-app/src/main/java/com/uid2/dev/ui/views/IdentityInputView.kt, dev-app/src/main/java/com/uid2/dev/ui/views/UserIdentityView.kt, dev-app/src/main/java/com/uid2/dev/utils/ByteArrayEx.kt, dev-app/src/main/res/values/strings.xml, sdk/src/main/java/com/uid2/UID2Client.kt, sdk/src/main/java/com/uid2/UID2Exception.kt, sdk/src/main/java/com/uid2/UID2Manager.kt, sdk/src/main/java/com/uid2/data/IdentityRequest.kt, sdk/src/main/java/com/uid2/extensions/ByteArrayEx.kt, sdk/src/main/java/com/uid2/extensions/StringEx.kt, sdk/src/main/java/com/uid2/network/DataEnvelope.kt, sdk/src/main/java/com/uid2/network/RefreshResponse.kt, sdk/src/main/java/com/uid2/network/ResponsePackage.kt, sdk/src/main/java/com/uid2/utils/InputUtils.kt, sdk/src/main/java/com/uid2/utils/KeyUtils.kt, sdk/src/main/java/com/uid2/utils/TimeUtils.kt, sdk/src/test/java/android/util/Base64.kt, sdk/src/test/java/com/uid2/UID2ClientTest.kt, sdk/src/test/java/com/uid2/UID2ManagerTest.kt, sdk/src/test/java/com/uid2/data/IdentityRequestTest.kt, sdk/src/test/java/com/uid2/extensions/StringExTest.kt, sdk/src/test/java/com/uid2/network/DataEnvelopeTest.kt, sdk/src/test/java/com/uid2/network/RefreshResponseTest.kt, sdk/src/test/java/com/uid2/utils/InputUtilsTest.kt
To test, refer to https://atlassian.thetradedesk.com/confluence/pages/viewpage.action?pageId=282321742
=> Implement support for Client Side Token Generation

sdk/src/main/java/com/uid2/UID2Client.kt, sdk/src/main/java/com/uid2/UID2Exception.kt, sdk/src/main/java/com/uid2/network/DefaultNetworkSession.kt, sdk/src/main/java/com/uid2/network/NetworkSession.kt
- We now extract any response text included in a response that's associated with a HTTP failure
- We now both log and include any error response text in the exception raised by the SDK
- I added some additional error handling that I took from the OpenPass SDK, to ensure we catch all potential IOException's
=> Improve error reporting by including optional error message

README.md
Remove duplicate info that will be added into unifiedid.com via [this PR](https://github.com/IABTechLab/uid2docs/pull/581)
=> Syw UID2-3502 fix android doco

build.gradle, dev-app/build.gradle, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, gradlew, sdk/src/test/java/com/uid2/UID2ManagerTest.kt
This PR bumps a number of dependencies:
- Kotlin 2.0 (+ Compose Compiler Plugin)
- Gradle
- AppCompat
After bumping Kotlin, a number of UTs started failing in Android Studio due to missing mocked methods.
=> [Dependencies] Update to K2

gradle/libs.versions.toml, sdk/build.gradle, sdk/src/test/java/com/uid2/UID2ClientTest.kt, sdk/src/test/java/com/uid2/UID2ManagerTest.kt, sdk/src/test/java/com/uid2/extensions/StringExTest.kt, sdk/src/test/java/com/uid2/network/DefaultNetworkSessionTest.kt, sdk/src/test/java/com/uid2/storage/FileStorageManagerTest.kt, sdk/src/test/java/com/uid2/utils/InputUtilsTest.kt
We are now using MockK for mocking, instead of Mockito. One of the main drivers for this is that we were stuck on an older version of Mockito, due to JVM versions. I had wanted to use MockK instead of a while, so decided to do this to allow us to be running the latest version - before we enable renovate.
=> Migrate Unit Tests to MockK

sdk/src/main/java/com/uid2/network/DefaultNetworkSession.kt, sdk/src/main/java/com/uid2/storage/FileStorageManager.kt, sdk/src/test/java/com/uid2/network/DefaultNetworkSessionTest.kt
This PR includes:
- We now assume that all network communication is done via HTTPS
- We now include explicit comments about how the identity is stored on the local device
=> Minor security updates

sdk/src/main/java/com/uid2/UID2Manager.kt, sdk/src/test/java/com/uid2/UID2ManagerTest.kt, securesignals-gma/src/main/java/com/uid2/securesignals/gma/UID2MediationAdapter.kt, securesignals-ima/src/main/java/com/uid2/securesignals/ima/UID2SecureSignalsAdapter.kt
This allows for multiple listeners to be attached to the same event, avoiding multiple uses of it clashing.
=> Refactor to allow multiple initialization listeners to be attached

.github/workflows/build.yml, .github/workflows/release.yml, build.gradle, common.gradle, dev-app/build.gradle, gradle.properties, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, prebid/build.gradle, sdk/build.gradle, securesignals-gma-dev-app/build.gradle, securesignals-gma/build.gradle, securesignals-ima-dev-app/build.gradle, securesignals-ima/build.gradle, settings.gradle
- A bump of dependencies, including Gradle, AGP, Spotless (including Ktlint), etc
- Upgraded to Dokka v2 Plugin
- Upgrade gradle configuration to avoid deprecated space assignment syntax
- Update GitHub workflow scripts
=> [Dependencies] Update dependencies (19th Feb 2025)
